server:
  port: 8081

#logging:
#  config: classpath:logback-spring.xml

spring:
  application:
    name: land-crowdfunding
  #  redis:
  #    host: 127.0.0.1
  #    port: 6379
  #    password: Kevin614718
  #    database: 2
  #  rabbitmq:
  #    host: 127.0.0.1
  #    port: 5672
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/land_crowdfunding?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl